- name: Deploy to VM via SSH
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.GCE_HOST }}
    username: ${{ secrets.GCE_USER }}
    key: ${{ secrets.GCE_SSH_KEY }}
    port: 22
    debug: true
    script: |
      cd ~/gcp-node-automation
      git pull origin main
      cd app
      npm install
      pm2 restart node-app
